name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job 1: Linting (flake8)
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - name: Install dependencies
        run: |
          pip install -r src/requirements.txt
      - name: Run flake8
        run: |
          pip install flake8
          flake8 .

  # Job 2: Running tests (pytest)
  tests:
    runs-on: ubuntu-latest
    needs: lint  # Run tests after linting
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - name: Install dependencies
        run: |
          pip install -r src/requirements.txt
      - name: Run tests
        run: |
          pip install pytest
          pytest --maxfail=1 --disable-warnings -q

  # Job 3: Build Docker image
  docker_build:
    runs-on: ubuntu-latest
    needs: tests  # Build Docker image only after tests are successful
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      - name: Build Docker image
        run: |
          docker build -t your-dockerhub-username/syspulse-app .

  # Optional Job 4: Push to DockerHub (only if you want)
  docker_push:
    runs-on: ubuntu-latest
    needs: docker_build
    steps:
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker image
        run: |
          docker push your-dockerhub-username/syspulse-app:latest
